This notebook is on features that were extracted with [pyradiomics](https://github.com/Radiomics/pyradiomics) from 813 lung cancer patients' CT-Scans at Cleveland Clinic.

In [1]:
import pandas as pd
import numpy as np

In [2]:
features = pd.read_csv('results_4_with_names.csv')
features.set_index('Unnamed: 0', inplace=True)
features.index.name = 'Patient_ID'

In [7]:
features.shape

(813, 128)

*813 patients and 128 features for each patient. 21 of these are 'diagnostic' features which will be discussed below. that leaves about 107 features for each patient.*

#### The features are as follows:

In [3]:
list(features.columns)

['diagnostics_Versions_PyRadiomics',
 'diagnostics_Versions_Numpy',
 'diagnostics_Versions_SimpleITK',
 'diagnostics_Versions_PyWavelet',
 'diagnostics_Versions_Python',
 'diagnostics_Configuration_Settings',
 'diagnostics_Configuration_EnabledImageTypes',
 'diagnostics_Image-original_Hash',
 'diagnostics_Image-original_Spacing',
 'diagnostics_Image-original_Size',
 'diagnostics_Image-original_Mean',
 'diagnostics_Image-original_Minimum',
 'diagnostics_Image-original_Maximum',
 'diagnostics_Mask-original_Hash',
 'diagnostics_Mask-original_Spacing',
 'diagnostics_Mask-original_Size',
 'diagnostics_Mask-original_BoundingBox',
 'diagnostics_Mask-original_VoxelNum',
 'diagnostics_Mask-original_VolumeNum',
 'diagnostics_Mask-original_CenterOfMassIndex',
 'diagnostics_Mask-original_CenterOfMass',
 'original_shape_Elongation',
 'original_shape_Flatness',
 'original_shape_LeastAxisLength',
 'original_shape_MajorAxisLength',
 'original_shape_Maximum2DDiameterColumn',
 'original_shape_Maximum2DD

### Counting the Features in the Different Categories:

In [4]:
first_two_words_feature_names = [ '_'.join(item.split('_')[:2]) for item in list(features.columns) ]
from collections import Counter
counter_dict = Counter(first_two_words_feature_names)
for key, value in counter_dict.items():
    print(key + ' ' + str(value))

diagnostics_Configuration 2
original_glcm 24
original_firstorder 18
diagnostics_Versions 5
original_glszm 16
original_ngtdm 5
diagnostics_Mask-original 8
original_glrlm 16
original_gldm 14
original_shape 14
diagnostics_Image-original 6


## The features come in 7 categories: 

### ** 0. Diagnostics **

These are not features but just 'diagnostics'. 21 of these in total.
These come in multiple subgroups:
a) *diagnostics_Versions* : These are the same values for all patients. can be useful for debugging if one needs to regenerate these numbers in the future or calculate the same for other images using the same version.

b) *diagnostics_Configuration* Consider the same for all images not meanignful till further notice/exploration. 

c) *diagnostics_Image-original* : Characteristics of the image/file. Some are the same for all patients and some are not for example the size of the image series (how many images in the series) changes from patient to patient.

d) *diagnostics_Mask-original* : Characteristics of the Mask. I am curious if these are captured by the calculated features : for example 'diagnostics_Mask-original_VoxelNum' seemst o capture the number of voxels but there may be a feature that has the same value as this. Check?




### ** 1) Original Shape Features** (14)

Describe the three-dimensional size and shape of the ROI

### ** 2) Original First Order Features** (18)

First-order statistics describe the distribution of voxel intensities within the image region defined by the mask 
through commonly used and basic metrics.

### ** 3)  "Gray Level Co-occurrence Matrix (GLCM)" Features** (24)

A *Gray Level Co-occurrence Matrix (GLCM)* of size $N_g \times N_g$ describes the second-order joint probability
  function of an image region constrained by the mask and is defined as $\textbf{P}(i,j|\delta,\theta)$.
  The $(i,j)^{\text{th}}$ element of this matrix represents the number of times the combination of
  levels $i$ and $j$ occur in two pixels in the image, that are separated by a distance of $\delta$
  pixels along angle $\theta$.


### ** 4)  "Gray Level Dependence Matrix (GLDM)" Features** (14)

A Gray Level Dependence Matrix (GLDM) quantifies gray level dependencies in an image.
A gray level dependency is defined as a the number of connected voxels within distance $\delta$ that are dependent on the center voxel.


### ** 5) Gray Level Run Length Matrix** (16)

Original GLRLM Features length in number of pixels, of consecutive pixels that have the same gray level value.

### **6) 16 GLSZM Features** (16)

These quantify gray level zones in an image. A gray level zone is defined as a the number
  of connected voxels that share the same gray level intensity.
  
### ** 7) NGTDM Features ** (5)
 
Neighbouring Gray Tone Difference Matrix measures the difference between a gray value and the average gray value of its neighbours within distance $\delta$.


##### To View Some Values for Each of the Feature Categories, change the feature_category variable's value and run the cell below:

In [5]:
feature_category = 'diagnostics_Mask-original'
features.loc[:, [item for item in list(features.columns) if item.startswith(feature_category)]].head()

diagnostics_Mask-original_Hash  \
Patient_ID                                             
P0002       1d5d805a4c63753953bdfef2ab8e33d70262b862   
P0003       f85cce9c5b06b65a3e2d31ddffc228618939ec03   
P0005       c7f00370a59b5efa8c3d8fbbcef707d84db9774c   
P0008       2f65743a563e2a20c039fa1cf45c30da16b87aa6   
P0015       35c48947bf004155943b31824e3d600a930ce68b   

           diagnostics_Mask-original_Spacing diagnostics_Mask-original_Size  \
Patient_ID                                                                    
P0002              (1.171875, 1.171875, 3.0)                (512, 512, 129)   
P0003              (1.171875, 1.171875, 3.0)                (512, 512, 131)   
P0005              (1.171875, 1.171875, 3.0)                (512, 512, 145)   
P0008              (1.171875, 1.171875, 3.0)                (512, 512, 121)   
P0015              (1.171875, 1.171875, 3.0)                (512, 512, 137)   

           diagnostics_Mask-original_BoundingBox  \
Patient_ID                                         
P0002                  (151, 230, 54, 20, 29, 6)   
P0003                  (212, 294, 94, 25, 18, 8)   
P0005                (169, 295, 100, 26, 27, 10)   
P0008                 (132, 265, 62, 63, 59, 23)   
P0015                 (197, 267, 81, 63, 60, 24)   

            diagnostics_Mask-original_VoxelNum  \
Patient_ID                                       
P0002                                      706   
P0003                                     1153   
P0005                                     2293   
P0008                                    33615   
P0015                                    27947   

            diagnostics_Mask-original_VolumeNum  \
Patient_ID                                        
P0002                                         1   
P0003                                         1   
P0005                                         1   
P0008                                         1   
P0015                                         1   

                  diagnostics_Mask-original_CenterOfMassIndex  \
Patient_ID                                                      
P0002       (161.44192634560906, 242.9815864022663, 56.665...   
P0003       (224.1699913269731, 303.5021682567216, 97.1405...   
P0005       (180.82250327082426, 307.5381596162233, 104.82...   
P0008       (166.4716049382716, 293.3513907481779, 72.5782...   
P0015       (229.14337853794683, 297.09596736680146, 91.68...   

                       diagnostics_Mask-original_CenterOfMass  
Patient_ID                                                     
P0002       (-110.8102425637394, 62.74404656515583, -582.0...  
P0003       (-37.300791413703394, 84.66660342584561, -611....  
P0005       (-88.09862897950282, 97.3962808002617, -700.01...  
P0008       (-104.91608796296296, 124.77116103302097, -913...  
P0015       (-31.47260327584354, 137.15933675797044, 385.0...

In [6]:
features.head()

diagnostics_Versions_PyRadiomics diagnostics_Versions_Numpy  \
Patient_ID                                                               
P0002                             0+unknown                     1.14.1   
P0003                             0+unknown                     1.14.1   
P0005                             0+unknown                     1.14.1   
P0008                             0+unknown                     1.14.1   
P0015                             0+unknown                     1.14.1   

           diagnostics_Versions_SimpleITK diagnostics_Versions_PyWavelet  \
Patient_ID                                                                 
P0002                               1.1.0                          1.0.1   
P0003                               1.1.0                          1.0.1   
P0005                               1.1.0                          1.0.1   
P0008                               1.1.0                          1.0.1   
P0015                               1.1.0                          1.0.1   

           diagnostics_Versions_Python  \
Patient_ID                               
P0002                            3.6.2   
P0003                            3.6.2   
P0005                            3.6.2   
P0008                            3.6.2   
P0015                            3.6.2   

                           diagnostics_Configuration_Settings  \
Patient_ID                                                      
P0002       {'minimumROIDimensions': 2, 'minimumROISize': ...   
P0003       {'minimumROIDimensions': 2, 'minimumROISize': ...   
P0005       {'minimumROIDimensions': 2, 'minimumROISize': ...   
P0008       {'minimumROIDimensions': 2, 'minimumROISize': ...   
P0015       {'minimumROIDimensions': 2, 'minimumROISize': ...   

           diagnostics_Configuration_EnabledImageTypes  \
Patient_ID                                               
P0002                                 {'Original': {}}   
P0003                                 {'Original': {}}   
P0005                                 {'Original': {}}   
P0008                                 {'Original': {}}   
P0015                                 {'Original': {}}   

                     diagnostics_Image-original_Hash  \
Patient_ID                                             
P0002       f9d241fb1777ecf697740ff73112fdda238e568e   
P0003       30a1544a237665296e593a6f8e7c22191d14e101   
P0005       9f8641c7e7d1ab04ee8174bbec4e36203a9cafe1   
P0008       1c1dc942aadcc74b3b319e0b6114e0378cc9bee8   
P0015       980ff8a6a53f71f56245ba7980f54ee515d5040d   

           diagnostics_Image-original_Spacing diagnostics_Image-original_Size  \
Patient_ID                                                                      
P0002               (1.171875, 1.171875, 3.0)                 (512, 512, 129)   
P0003               (1.171875, 1.171875, 3.0)                 (512, 512, 131)   
P0005               (1.171875, 1.171875, 3.0)                 (512, 512, 145)   
P0008               (1.171875, 1.171875, 3.0)                 (512, 512, 121)   
P0015               (1.171875, 1.171875, 3.0)                 (512, 512, 137)   

                     ...            \
Patient_ID           ...             
P0002                ...             
P0003                ...             
P0005                ...             
P0008                ...             
P0015                ...             

            original_glszm_SmallAreaHighGrayLevelEmphasis  \
Patient_ID                                                  
P0002                                          300.987090   
P0003                                          378.437162   
P0005                                          434.543541   
P0008                                          509.233039   
P0015                                          829.625744   

            original_glszm_SmallAreaLowGrayLevelEmphasis  \
Patient_ID                                                 
P0002                    

Next Steps:

1) Check that all features exist for all patients, no NaNs.
2) Check for redundancy of the features. for example:
a) I got a warning "GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated"
b) Check if some diagnostic features are also found in actual features, predominantly first_order, shape features.
3) How could one examine the value of each one of these features: prediction without overfitting? Logistic Regression.